# Generated by Django 5.2.10 on 2026-02-09 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(help_text='Official Faculty ID Number', max_length=50, unique=True)),
                ('faculty_id', models.CharField(blank=True, help_text='System-generated Faculty Login ID', max_length=30, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('caste', models.CharField(blank=True, max_length=100)),
                ('reservation_category', models.CharField(blank=True, max_length=100)),
                ('minority_indicator', models.CharField(blank=True, max_length=50)),
                ('mobile_no', models.CharField(blank=True, max_length=15)),
                ('other_mobile_no', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Official faculty email', max_length=254, null=True)),
                ('is_physically_challenged', models.CharField(blank=True, max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('aadhar_no', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('licence_number', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty',
                'ordering': ['id_no'],
            },
        ),
    ]
