# Generated by Django 5.2.10 on 2026-02-09 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_ticket_no', models.CharField(max_length=30, unique=True)),
                ('admission_no', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Auto-generated student email', max_length=254, null=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, help_text='M / F / O', max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('convenor', models.CharField(blank=True, max_length=50)),
                ('student_mobile', models.CharField(blank=True, max_length=10)),
                ('parent_mobile', models.CharField(blank=True, max_length=10)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('caste', models.CharField(blank=True, max_length=50)),
                ('aadhar', models.CharField(blank=True, max_length=12)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
                'ordering': ['hall_ticket_no'],
            },
        ),
    ]
